version: 2.1
orbs:
  ruby: circleci/ruby@1.1.4

jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker build -t bugzilla .
      - run: docker run -v "$PWD:/root/bugzilla" -ti bugzilla ./entrypoint.sh
