require 'bugzilla/version'
require 'bugzilla/bug'
require 'bugzilla/bugzilla'
require 'bugzilla/classification'
require 'bugzilla/group'
require 'bugzilla/plugin'
require 'bugzilla/product'
require 'bugzilla/user'
require 'bugzilla/utils'
require 'bugzilla/version'
require 'bugzilla/xmlrpc'

